### ISSUE TITLE
Automatically Generate the Table of Protobuf Types

### ISSUE THREAD

**Issue by emamanto** [northern-bites/nbites#445]
Someone needs to work some cmake magic so that the type table gets configured based on what protobufs we've compiled.

**Comment by philipkoch** [comment]
What / where is a "type table"?

**Comment by emamanto** [comment]
This was something I hacked in during the frantic qtool update of 2013. I'm guessing you don't use it anymore.

**Comment by philipkoch** [comment]
Ok cool!  I'm going to go ahead and close this then.
