### ISSUE TITLE
Monitor-like tool in qt

### ISSUE THREAD

**Issue by joshimhoff** [northern-bites/nbites#644]
#440 needs to happen first, but it would be nice if we had a monitor-like tool for adjusting camera params. Now that we use the BH camera driver, monitor is much less helpful. 

Not absolutely crucial but definitely nice.

**Comment by philipkoch** [comment]
We have a 'tool' for adjusting params, but I'm not familiar with 'monitor.'

**Comment by dzeller** [comment]
Monitor was a tool produced by Aldebaran that streamed images and allowed
you to modify camera params on the fly. We basically have this now.

**Comment by philipkoch** [comment]
The reclamation of `issues` continues.
