### ISSUE TITLE
Separate Man and NaoQi

### ISSUE THREAD

**Issue by dzeller** [northern-bites/nbites#677]
It might be desirable for us to put a layer of separation between Man and Naoqi so that we don't have to restart Naoqi to restart Man.
One way this could be achieved is by having an intermediate Naoqi module which in turn can construct and destroy instances of Man as needed.

One thing that needs to happen for this to work is that we CANNOT have code destruction issues. Our current memory leaks which don't cause issues could turn into dangerous memory leaks and impact our ability to play. See #659

**Comment by philipkoch** [comment]
libboss is not final.  However, in the interest of a clean start [w.r.t. issues] I'm closing this (go Team Zeller!).
