### ISSUE TITLE
Fix robot sit-down

### ISSUE THREAD

**Issue by mmmaher** [northern-bites/nbites#734]
When our robots sit down during the Game Controller's "Game finished" or "Half over", or during a man stop, they fall over.

**Comment by itumanen** [comment]
Possible quick fix for this in these particular contexts is #737 and then manually shutting off stiffnesses, since standing with stretched knees and stiffnesses on is much more stable than sitting

**Comment by littleguy230** [comment]
I've been restarting the robots a lot while they're in game finished to try to fix another bug and every time they sit down they haven't fallen over.
