### ISSUE TITLE
Change the way we spin

### ISSUE THREAD

**Issue by mmmaher** [northern-bites/nbites#735]
1. Instead of a constant spin, it may be worthwhile to spin, stop, spin, stop, etc. 
2. A bug to point out - when we do our full spin, we never get all the way around and quite often end up missing the ball completely because we didn't turn far enough.

**Comment by echown** [comment]
Other things that need to be improved:
1) There is no point spinning past the edge of the field. If we're near the edge of the field then we should only spin on the side where there is open field.
2) We should spin, stop, spin, stop, . . .  More to the point - we should test the two types of spinning by simply putting balls on the field and testing how good they are at detecting them.
